name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ---- PHP / Laravel setup ----
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Generate app key & cache config
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache

      # ---- Node / Vite setup ----
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install JS dependencies
        run: npm ci

      - name: Build front-end assets
        run: npm run build

      # ---- Run Laravel tests ----
      - name: Run PHPUnit tests
        env:
            APP_ENV: testing
            APP_KEY: base64:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=
            DB_CONNECTION: sqlite
            DB_DATABASE: ":memory:"
        run: php artisan test

